import { execFile } from "node:child_process";
import { mkdir, access, writeFile, readFile, unlink, mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

export interface TaskWarriorConfig {
  taskBin: string;
  taskData: string;
  taskRc: string;
}

export interface ExecResult {
  stdout: string;
  stderr: string;
}

const RC_OVERRIDES = [
  "rc.confirmation=off",
  "rc.bulk=0",
  "rc.verbose=nothing",
];

export function getConfig(): TaskWarriorConfig {
  const taskData = process.env.TASKDATA;
  if (!taskData) {
    throw new Error(
      "TASKDATA environment variable is required. " +
        "Set it to a project-specific directory, e.g. ~/.local/share/taskwarrior-mcp/my-project"
    );
  }

  return {
    taskBin: process.env.TASK_BIN || "task",
    taskData,
    taskRc: process.env.TASKRC || join(taskData, ".taskrc"),
  };
}

export async function ensureSetup(config: TaskWarriorConfig): Promise<void> {
  await mkdir(config.taskData, { recursive: true });

  try {
    await access(config.taskRc);
  } catch {
    const rcContent = [
      "# Auto-generated by taskwarrior-mcp",
      `data.location=${config.taskData}`,
      "confirmation=off",
      "bulk=0",
      "verbose=nothing",
      "",
      "# UDAs for agent workflow",
      "uda.agent.type=string",
      "uda.agent.label=Agent",
      "uda.has_doc.type=string",
      "uda.has_doc.label=Has Doc",
      "uda.has_doc.values=yes",
      "",
    ].join("\n");
    await writeFile(config.taskRc, rcContent, "utf-8");
  }
}

function buildArgs(config: TaskWarriorConfig, args: string[]): string[] {
  return [`rc:${config.taskRc}`, `rc.data.location=${config.taskData}`, ...RC_OVERRIDES, ...args];
}

export function run(config: TaskWarriorConfig, args: string[]): Promise<ExecResult> {
  const fullArgs = buildArgs(config, args);

  return new Promise((resolve, reject) => {
    execFile(config.taskBin, fullArgs, { maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        const exitCode = error.code;
        // TaskWarrior returns exit code 1 for "no matching tasks" which is not an error
        if (exitCode === 1 && !stderr.trim()) {
          resolve({ stdout: stdout || "", stderr: "" });
          return;
        }
        reject(new Error(stderr.trim() || error.message));
        return;
      }
      resolve({ stdout: stdout || "", stderr: stderr || "" });
    });
  });
}

export async function exportTasks(config: TaskWarriorConfig, filter: string): Promise<unknown[]> {
  const args = filter ? [...filter.split(/\s+/), "export"] : ["export"];
  const result = await run(config, args);
  const trimmed = result.stdout.trim();
  if (!trimmed) return [];
  return JSON.parse(trimmed) as unknown[];
}

export async function addTask(
  config: TaskWarriorConfig,
  description: string,
  attrs: Record<string, string>,
  extraArgs: string[] = []
): Promise<string> {
  const args = ["add", description, ...extraArgs];
  for (const [key, value] of Object.entries(attrs)) {
    if (value) args.push(`${key}:${value}`);
  }
  const result = await run(config, args);
  return result.stdout.trim() || "Task added.";
}

export async function modifyTask(
  config: TaskWarriorConfig,
  filter: string,
  attrs: Record<string, string>,
  extraArgs: string[] = []
): Promise<string> {
  const args = [...filter.split(/\s+/), "modify", ...extraArgs];
  for (const [key, value] of Object.entries(attrs)) {
    if (value !== undefined) args.push(`${key}:${value}`);
  }
  const result = await run(config, args);
  return result.stdout.trim() || "Task modified.";
}

export async function taskCommand(
  config: TaskWarriorConfig,
  id: string,
  command: string,
  extraArgs: string[] = []
): Promise<string> {
  const args = [id, command, ...extraArgs];
  const result = await run(config, args);
  return result.stdout.trim() || `Task ${command} completed.`;
}

export async function undo(config: TaskWarriorConfig): Promise<string> {
  const result = await run(config, ["undo"]);
  return result.stdout.trim() || "Undo completed.";
}

export async function importTasks(config: TaskWarriorConfig, tasksJson: string): Promise<string> {
  const tmpDir = await mkdtemp(join(tmpdir(), "tw-import-"));
  const tmpFile = join(tmpDir, "import.json");
  try {
    await writeFile(tmpFile, tasksJson, "utf-8");
    const result = await run(config, ["import", tmpFile]);
    return result.stdout.trim() || "Import completed.";
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

function docsDir(config: TaskWarriorConfig): string {
  return join(config.taskData, "docs");
}

function docPath(config: TaskWarriorConfig, uuid: string): string {
  return join(docsDir(config), `${uuid}.md`);
}

async function resolveUuid(config: TaskWarriorConfig, id: string): Promise<string> {
  const tasks = await exportTasks(config, id);
  if (tasks.length === 0) throw new Error(`No task found matching '${id}'`);
  return (tasks[0] as Record<string, unknown>).uuid as string;
}

export async function writeDoc(config: TaskWarriorConfig, id: string, content: string): Promise<string> {
  const uuid = await resolveUuid(config, id);
  const dir = docsDir(config);
  await mkdir(dir, { recursive: true });
  await writeFile(docPath(config, uuid), content, "utf-8");
  // Tag the task and set has_doc UDA
  await modifyTask(config, uuid, { has_doc: "yes" }, ["+doc"]);
  return `Doc written for task ${uuid}.`;
}

export async function readDoc(config: TaskWarriorConfig, id: string): Promise<string | null> {
  const uuid = await resolveUuid(config, id);
  try {
    return await readFile(docPath(config, uuid), "utf-8");
  } catch {
    return null;
  }
}

export async function deleteDoc(config: TaskWarriorConfig, id: string): Promise<string> {
  const uuid = await resolveUuid(config, id);
  try {
    await unlink(docPath(config, uuid));
  } catch {
    // File may not exist, that's fine
  }
  // Remove tag and UDA
  await modifyTask(config, uuid, { has_doc: "" }, ["-doc"]);
  return `Doc deleted for task ${uuid}.`;
}

export async function getUnique(config: TaskWarriorConfig, attribute: string): Promise<string[]> {
  const result = await run(config, ["_unique", attribute]);
  const trimmed = result.stdout.trim();
  if (!trimmed) return [];
  const values = trimmed.split("\n").filter(Boolean);
  // TaskWarrior _unique tags returns comma-separated tag sets per task — split and deduplicate
  if (attribute === "tags") {
    const all = values.flatMap((v) => v.split(","));
    return [...new Set(all)];
  }
  return values;
}
