import { execFile } from "node:child_process";
import { mkdir, access, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface TaskWarriorConfig {
  taskBin: string;
  taskData: string;
  taskRc: string;
}

export interface ExecResult {
  stdout: string;
  stderr: string;
}

const RC_OVERRIDES = [
  "rc.confirmation=off",
  "rc.bulk=0",
  "rc.verbose=nothing",
];

export function getConfig(): TaskWarriorConfig {
  const taskData = process.env.TASKDATA;
  if (!taskData) {
    throw new Error(
      "TASKDATA environment variable is required. " +
        "Set it to a project-specific directory, e.g. ~/.local/share/taskwarrior-mcp/my-project"
    );
  }

  return {
    taskBin: process.env.TASK_BIN || "task",
    taskData,
    taskRc: process.env.TASKRC || join(taskData, ".taskrc"),
  };
}

export async function ensureSetup(config: TaskWarriorConfig): Promise<void> {
  await mkdir(config.taskData, { recursive: true });

  try {
    await access(config.taskRc);
  } catch {
    const rcContent = [
      "# Auto-generated by taskwarrior-mcp",
      `data.location=${config.taskData}`,
      "confirmation=off",
      "bulk=0",
      "verbose=nothing",
      "",
    ].join("\n");
    await writeFile(config.taskRc, rcContent, "utf-8");
  }
}

function buildArgs(config: TaskWarriorConfig, args: string[]): string[] {
  return [`rc:${config.taskRc}`, `rc.data.location=${config.taskData}`, ...RC_OVERRIDES, ...args];
}

export function run(config: TaskWarriorConfig, args: string[]): Promise<ExecResult> {
  const fullArgs = buildArgs(config, args);

  return new Promise((resolve, reject) => {
    execFile(config.taskBin, fullArgs, { maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        const exitCode = error.code;
        // TaskWarrior returns exit code 1 for "no matching tasks" which is not an error
        if (exitCode === 1 && !stderr.trim()) {
          resolve({ stdout: stdout || "", stderr: "" });
          return;
        }
        reject(new Error(stderr.trim() || error.message));
        return;
      }
      resolve({ stdout: stdout || "", stderr: stderr || "" });
    });
  });
}

export async function exportTasks(config: TaskWarriorConfig, filter: string): Promise<unknown[]> {
  const args = filter ? [...filter.split(/\s+/), "export"] : ["export"];
  const result = await run(config, args);
  const trimmed = result.stdout.trim();
  if (!trimmed) return [];
  return JSON.parse(trimmed) as unknown[];
}

export async function addTask(
  config: TaskWarriorConfig,
  description: string,
  attrs: Record<string, string>,
  extraArgs: string[] = []
): Promise<string> {
  const args = ["add", description, ...extraArgs];
  for (const [key, value] of Object.entries(attrs)) {
    if (value) args.push(`${key}:${value}`);
  }
  const result = await run(config, args);
  return result.stdout.trim() || "Task added.";
}

export async function modifyTask(
  config: TaskWarriorConfig,
  filter: string,
  attrs: Record<string, string>,
  extraArgs: string[] = []
): Promise<string> {
  const args = [...filter.split(/\s+/), "modify", ...extraArgs];
  for (const [key, value] of Object.entries(attrs)) {
    if (value) args.push(`${key}:${value}`);
  }
  const result = await run(config, args);
  return result.stdout.trim() || "Task modified.";
}

export async function taskCommand(
  config: TaskWarriorConfig,
  id: string,
  command: string,
  extraArgs: string[] = []
): Promise<string> {
  const args = [id, command, ...extraArgs];
  const result = await run(config, args);
  return result.stdout.trim() || `Task ${command} completed.`;
}

export async function undo(config: TaskWarriorConfig): Promise<string> {
  const result = await run(config, ["undo"]);
  return result.stdout.trim() || "Undo completed.";
}

export async function getUnique(config: TaskWarriorConfig, attribute: string): Promise<string[]> {
  const result = await run(config, ["_unique", attribute]);
  const trimmed = result.stdout.trim();
  if (!trimmed) return [];
  const values = trimmed.split("\n").filter(Boolean);
  // TaskWarrior _unique tags returns comma-separated tag sets per task — split and deduplicate
  if (attribute === "tags") {
    const all = values.flatMap((v) => v.split(","));
    return [...new Set(all)];
  }
  return values;
}
